Add markdown list example
CSS-Next/css-next pull request #91
Opened 2024-04-08 10:08 UTC by brechtDR

2024-04-08 15:11 UTC, una commented
A few suggestions for this list:

1. Put a clear headline that this is a draft list and not final
2. Add the MDN links (as linked through in the doc we all worked on) on the feature name
3. Add some indicator (like an emoji) for features we already flagged for discussion

2024-04-09 11:26 UTC, brechtDR commented
> A few suggestions for this list as per discussion:
> 
> 1. Put a clear headline that this is a draft list and not final

Done

> 2. Add the MDN links (as linked through in the doc we all worked on) on the feature name

Ongoing (done for CSS4)

> 3. Add some indicator (like an emoji) for features we already flagged for discussion

TBD in a meeting? "Which emoji, which items". We might have changed opinions a bit. Might be good to go over them next meeting.

> 4. Reduce subheadings, i.e. "flex properties" should go under "flexbox", "math functions" combined with "trigonometric functions", etc.

Done

> 5. Remove "properies", "modern", and "CSS" from titles

Done

2024-04-10 11:46 UTC, brechtDR commented
Added all the links I could find, some were missing.

2024-04-12 06:34 UTC, subuhunter commented on lists/proposal-rfc.md
>  * **Future/Next**: This category encompasses properties and features that are currently in development or proposed for future versions of CSS beyond CSS5. It serves as a preview of upcoming CSS that
Do we also need to mention the year here? Like "2024+"

2024-04-15 16:01 UTC, una commented on lists/proposal-rfc.md
>  * **Future/Next**: This category encompasses properties and features that are currently in development or proposed for future versions of CSS beyond CSS5. It serves as a preview of upcoming CSS that
2025+ will be the next version (2025 - 2031 based on our current versioning)

2024-04-22 15:25 UTC, Que-tin commented
https://github.com/CSS-Next/css-next/issues/89

2024-04-22 15:55 UTC, argyleink commented on lists/proposal-rfc.md
> +The term "CSS3" has been widely used to encompass various additions and enhancements to Cascading Style Sheets (CSS) since around 2010. However, as CSS continues to evolve with new features and speci
```suggestion
The term "CSS3" has been widely used to encompass various additions and enhancements to Cascading Style Sheets (CSS) since around 2010. However, as CSS continues to evolve with new features and specifications, the blanket term "CSS3" has become insufficient and misleading. This RFC proposes the categorization of CSS properties into distinct groups, namely CSS3, CSS4, and CSS5, to better organize and facilitate understanding of the evolving CSS landscape. This categorization aims to improve adoption and ease of teaching, while not having a direct impact towards the CSS Working Group (CSSWG) operations or the [Baseline initiative](https://web.dev/baseline). 
```

2024-04-22 15:56 UTC, argyleink commented on lists/proposal-rfc.md
> +Categorization is based on when new properties were introduced in a spec. This is to be browser(vendor) independent.
```suggestion
Categorization is based on when new properties were introduced in a spec. This is browser independent and implementation independent, though these factors are lightly taken into account.
```

2024-04-22 16:00 UTC, argyleink commented on lists/proposal-rfc.md
> +* **CSS3:** This category includes CSS properties and features introduced prior to the proposal to further categorize. It serves as a historical reference point for CSS advancements up to a certain p
```suggestion
* **CSS3:** This category was established before this community group began articulating levels and was defined by the CSSWG, and was designed to be open ended. It serves as a historical reference point for CSS advancements up to a certain point.
```

2024-04-26 13:01 UTC, brechtDR commented on lists/proposal-rfc.md
>  * **Future/Next**: This category encompasses properties and features that are currently in development or proposed for future versions of CSS beyond CSS5. It serves as a preview of upcoming CSS that
I agree, but not sure if we should add an "end" date already. As CSS features really come alive a lot more quickly the past few years. Versioning might have a need to go a bit faster than 6 years. Just a thought. (To clarify: not talking yearly, but rather "who knows, maybe 4 years")

2024-04-26 15:10 UTC, una commented on lists/proposal-rfc.md
>  * **Future/Next**: This category encompasses properties and features that are currently in development or proposed for future versions of CSS beyond CSS5. It serves as a preview of upcoming CSS that
When we used this timeline, it was more of a guide and not an absolute (and not all the features neatly fit into this definition set as there were a lot of exceptions). The phrasing here makes it sound like absolute cutoffs and like we used the dates as the primary mechanism (which was not true, it was an indicator, along with other indicators like spec level and browser support).

2024-04-29 15:46 UTC, una requested changes
Comments, discussed in meeting April 29.

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +Categorization is based on when new properties were introduced in a specification. This is browser independent and implementation independent, though these factors are lightly taken into account.
```suggestion
Categorization is based on a variety of factors with the primary factor being the general timeline that an API was initially specified in the CSS Working Group. Additionally, implementer interest and adoption were moderately taken into account in the categorization process.
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +* **CSS4:** Properties and features introduced in a spec between 2013 - 2018.
```suggestion
* **CSS4:** Properties and features introduced in a spec around 2013 - 2018.
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +* **CSS5:** Properties and features introduced in a spec between 2019 - 2024.
```suggestion
* **CSS5:** Properties and features introduced in a spec around 2019 - 2024.
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +* **Future/Next**: This category encompasses properties and features that are currently in development or proposed for future versions of CSS beyond CSS5. It serves as a preview of upcoming CSS that
```suggestion
* **Future/Next**: This category is a placeholder for properties and features that are currently in development or proposed for future versions of CSS beyond CSS5.
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +* New CSS properties and features will be categorized into Future/Next (name pending)
```suggestion
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +The term "CSS3" has been widely used to encompass various additions and enhancements to Cascading Style Sheets (CSS) since around 2010. However, as CSS continues to evolve with new features and speci
```suggestion
The term "CSS3" has been widely used to encompass various additions and enhancements to Cascading Style Sheets (CSS) since around 2010. However, as CSS continues to evolve with new features and specifications, the blanket term "CSS3" has become insufficient and misleading. This RFC proposes the categorization of CSS properties into distinct groups, namely CSS3, CSS4, and CSS5, to better organize and facilitate understanding of the evolving CSS landscape. This categorization aims to improve adoption and ease of teaching, while not having a direct impact towards the CSS Working Group (CSSWG) operations or the [Baseline initiative](https://github.com/web-platform-dx/web-features/blob/main/docs/baseline.md). 
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +* The categorization will not affect the numbering or operations of official CSS snapshots maintained by the CSSWG.
```suggestion
* The categorization will not affect the numbering or operations of official CSS snapshots maintained by the CSSWG and [Baseline initiative](https://github.com/web-platform-dx/web-features).
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +Clear categorization of CSS properties into CSS3, CSS4, CSS5, and Future/Next will provide developers, recruiters, and educators with a structured framework for understanding and discussing CSS advan
```suggestion
"Modern CSS" does not have any specific meaning or timeframe. Clear categorization of CSS properties into CSS3, CSS4, CSS5, and any future versions will provide developers, recruiters, employers, and educators with a structured framework for understanding and discussing CSS advancements and its evolution.
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +Educators will have a clearer roadmap for teaching CSS advancements and could even be divided in different classes, making it easier to introduce concepts to students.
```suggestion
Educators will have a clearer vocabulary and roadmap for teaching the evolution of CSS and better categorize modern CSS features.
```

2024-04-29 15:46 UTC, una commented on lists/proposal-rfc.md
> +The categorization of CSS properties into CSS3, CSS4, CSS5, and Future/Next offers a solution to the ambiguity surrounding the term "CSS3" and provides a structured framework for understanding and di
```suggestion
The categorization of CSS properties into CSS3, CSS4, CSS5, and any future versions offers a solution to the ambiguity surrounding the terms "CSS3" and "modern CSS", while providing a structured framework for understanding and discussing CSS advancements. By implementing this proposal, we can improve adoption, simplify education, and better organize the evolving landscape of CSS.
```

2024-04-29 15:50 UTC, brechtDR commented on lists/proposal-rfc.md
> +
```suggestion
```

2024-04-29 15:55 UTC, una approved these changes

2024-04-29 15:55 UTC, merged